import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
data =  pd.read_csv(r'C:\Users\VISHNU\Downloads\tip(in).csv')
print("Dataset is like:")
print("shape: ",data.shape)
print("---------------------------------")
print("info:")
print(data.info())
print("---------------------------------")
print("date types: ")
print(data.dtypes)
print("---------------------------------")
print("data description: ")
print(data.describe())
print("---------------------------------")
print("checking for missing values: ")
print(data.isnull().sum())
print("---------------------------------")
print("checking for duplicate values: ")
print(data.duplicated().sum())
data.drop_duplicates(inplace=True)
#trend analysis
plt.plot(data.index,data['total_bill'],marker='o',linestyle='dashed',color='orange')
plt.title('Total Bill vs Index')
plt.xlabel('Index')
plt.ylabel('Total Bill')
plt.show()
plt.bar(['male','female'],data["total_bill"])
plt.show()